- name: variables
  hosts: localhost
  vars: #variables declaration
    course: "Ansible"
    trainer: "sivakumar"
    duration: "120hrs"
  tasks:
  - name: print information
    ansible.builtin.debug:
      msg: "hi, we are learning{{course}} from {{trainer}}{{duration}}"
